export const ERROR_CODES = {
  // Authentication & Authorization
  INVALID_HASH: 'INVALID_HASH',
  AUTHENTICATION_ERROR: 'AUTHENTICATION_ERROR',
  AUTHORIZATION_ERROR: 'AUTHORIZATION_ERROR',
  ACCESS_DENIED: 'ACCESS_DENIED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_TOKEN: 'INVALID_TOKEN',

  // Transaction & Payment
  TRANSACTION_NOT_FOUND: 'TRANSACTION_NOT_FOUND',
  TRANSACTION_FAILED: 'TRANSACTION_FAILED',
  TRANSACTION_ALREADY_COMPLETED: 'TRANSACTION_ALREADY_COMPLETED',
  TRANSACTION_ALREADY_INITIATED: 'TRANSACTION_ALREADY_INITIATED',
  TRANSACTION_ALREADY_REFUNDED: 'TRANSACTION_ALREADY_REFUNDED',
  TRANSACTION_ALREADY_SETTLED: 'TRANSACTION_ALREADY_SETTLED',
  TRANSACTION_EXPIRED: 'TRANSACTION_EXPIRED',

  // Merchant & Integration
  INVALID_MERCHANT: 'INVALID_MERCHANT',
  INVALID_INTEGRATION: 'INVALID_INTEGRATION',
  MERCHANT_NOT_FOUND: 'MERCHANT_NOT_FOUND',
  INTEGRATION_NOT_ENABLED: 'INTEGRATION_NOT_ENABLED',

  // Payment Processing
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  INVALID_CARD: 'INVALID_CARD',
  CARD_DECLINED: 'CARD_DECLINED',
  INVALID_PAYMENT_REQUEST: 'INVALID_PAYMENT_REQUEST',
  PAYMENT_METHOD_NOT_SUPPORTED: 'PAYMENT_METHOD_NOT_SUPPORTED',

  // System & Network
  FEATURE_DISABLED: 'FEATURE_DISABLED',
  NETWORK_ERROR: 'NETWORK_ERROR',
  TIMEOUT_ERROR: 'TIMEOUT_ERROR',
  CIRCUIT_BREAKER_OPEN: 'CIRCUIT_BREAKER_OPEN',
  PROVIDER_ERROR: 'PROVIDER_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',

  // Validation & Input
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_PARAM: 'INVALID_PARAM',
  MISSING_HEADER_PARAMETER: 'MISSING_HEADER_PARAMETER',
  INVALID_AMOUNT: 'INVALID_AMOUNT',
  AMOUNT_EXCEEDS_LIMIT: 'AMOUNT_EXCEEDS_LIMIT',

  // Rate Limiting
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',

  // Refunds
  REFUND_AMOUNT_EXCEEDED: 'REFUND_AMOUNT_EXCEEDED',
  REFUND_NOT_ALLOWED: 'REFUND_NOT_ALLOWED',
  REFUND_FAILED: 'REFUND_FAILED',

  // Settlement
  SETTLEMENT_FAILED: 'SETTLEMENT_FAILED',
  SETTLEMENT_NOT_ALLOWED: 'SETTLEMENT_NOT_ALLOWED',

  // OTP & Verification
  INVALID_OTP: 'INVALID_OTP',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_RETRIES_EXCEEDED: 'OTP_RETRIES_EXCEEDED',
  VERIFICATION_FAILED: 'VERIFICATION_FAILED',

  // General
  NOT_FOUND: 'NOT_FOUND',
  BAD_REQUEST: 'BAD_REQUEST',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  FORBIDDEN: 'FORBIDDEN',
  CONFLICT: 'CONFLICT',
  UNPROCESSABLE_ENTITY: 'UNPROCESSABLE_ENTITY',

  // Provider specific
  KONGAPAY_OTP_RETRIES_LEFT: 'KONGAPAY_OTP_RETRIES_LEFT',
  CARD_SERVICE_RETRIES_LEFT_ERROR_CODE: 'CARD_SERVICE_RETRIES_LEFT_ERROR_CODE',
  CARD_SERVICE_INSUFFICENT_BALANCE_CODE: 'CARD_SERVICE_INSUFFICENT_BALANCE_CODE',
  MANDATE_OTP_RETRIES_LEFT: 'MANDATE_OTP_RETRIES_LEFT',

  // Customer & Data
  CUSTOMER_ID_NOT_FOUND: 'CUSTOMER_ID_NOT_FOUND',
  MISSING_MERCHANT_REFERENCE: 'MISSING_MERCHANT_REFERENCE',
  DUPLICATE_TRANSACTION: 'DUPLICATE_TRANSACTION',
} as const;

export const ERROR_MESSAGES = {
  // Authentication & Authorization
  [ERROR_CODES.INVALID_HASH]: 'Invalid hash provided',
  [ERROR_CODES.AUTHENTICATION_ERROR]: 'Authentication failed',
  [ERROR_CODES.AUTHORIZATION_ERROR]: 'Access denied',
  [ERROR_CODES.ACCESS_DENIED]: 'Access denied',
  [ERROR_CODES.TOKEN_EXPIRED]: 'Token has expired',
  [ERROR_CODES.INVALID_TOKEN]: 'Invalid token provided',

  // Transaction & Payment
  [ERROR_CODES.TRANSACTION_NOT_FOUND]: 'Transaction not found',
  [ERROR_CODES.TRANSACTION_FAILED]: 'Transaction failed',
  [ERROR_CODES.TRANSACTION_ALREADY_COMPLETED]: 'Transaction already completed',
  [ERROR_CODES.TRANSACTION_ALREADY_INITIATED]: 'Transaction already initiated',
  [ERROR_CODES.TRANSACTION_ALREADY_REFUNDED]: 'Transaction already refunded',
  [ERROR_CODES.TRANSACTION_ALREADY_SETTLED]: 'Transaction already settled',
  [ERROR_CODES.TRANSACTION_EXPIRED]: 'Transaction has expired',

  // Merchant & Integration
  [ERROR_CODES.INVALID_MERCHANT]: 'Invalid merchant credentials',
  [ERROR_CODES.INVALID_INTEGRATION]: 'Invalid integration credentials',
  [ERROR_CODES.MERCHANT_NOT_FOUND]: 'Merchant not found',
  [ERROR_CODES.INTEGRATION_NOT_ENABLED]: 'Integration not enabled',

  // Payment Processing
  [ERROR_CODES.INSUFFICIENT_BALANCE]: 'Insufficient balance',
  [ERROR_CODES.INVALID_CARD]: 'Invalid card details',
  [ERROR_CODES.CARD_DECLINED]: 'Card declined by issuer',
  [ERROR_CODES.INVALID_PAYMENT_REQUEST]: 'Invalid payment request',
  [ERROR_CODES.PAYMENT_METHOD_NOT_SUPPORTED]: 'Payment method not supported',

  // System & Network
  [ERROR_CODES.FEATURE_DISABLED]: 'This feature is currently disabled',
  [ERROR_CODES.NETWORK_ERROR]: 'Network error occurred',
  [ERROR_CODES.TIMEOUT_ERROR]: 'Request timed out',
  [ERROR_CODES.CIRCUIT_BREAKER_OPEN]: 'Service temporarily unavailable',
  [ERROR_CODES.PROVIDER_ERROR]: 'Payment provider error',
  [ERROR_CODES.SERVICE_UNAVAILABLE]: 'Service temporarily unavailable',

  // Validation & Input
  [ERROR_CODES.VALIDATION_ERROR]: 'Validation error',
  [ERROR_CODES.INVALID_PARAM]: 'Invalid parameter provided',
  [ERROR_CODES.MISSING_HEADER_PARAMETER]: 'Missing required header parameter',
  [ERROR_CODES.INVALID_AMOUNT]: 'Invalid amount provided',
  [ERROR_CODES.AMOUNT_EXCEEDS_LIMIT]: 'Amount exceeds maximum limit',

  // Rate Limiting
  [ERROR_CODES.RATE_LIMIT_EXCEEDED]: 'Rate limit exceeded',
  [ERROR_CODES.TOO_MANY_REQUESTS]: 'Too many requests, please try again later',

  // Refunds
  [ERROR_CODES.REFUND_AMOUNT_EXCEEDED]: 'Refund amount exceeds original transaction amount',
  [ERROR_CODES.REFUND_NOT_ALLOWED]: 'Refund not allowed for this transaction',
  [ERROR_CODES.REFUND_FAILED]: 'Refund processing failed',

  // Settlement
  [ERROR_CODES.SETTLEMENT_FAILED]: 'Settlement processing failed',
  [ERROR_CODES.SETTLEMENT_NOT_ALLOWED]: 'Settlement not allowed for this transaction',

  // OTP & Verification
  [ERROR_CODES.INVALID_OTP]: 'Invalid OTP provided',
  [ERROR_CODES.OTP_EXPIRED]: 'OTP has expired',
  [ERROR_CODES.OTP_RETRIES_EXCEEDED]: 'Maximum OTP retry attempts exceeded',
  [ERROR_CODES.VERIFICATION_FAILED]: 'Verification failed',

  // General
  [ERROR_CODES.NOT_FOUND]: 'Resource not found',
  [ERROR_CODES.BAD_REQUEST]: 'Bad request',
  [ERROR_CODES.INTERNAL_SERVER_ERROR]: 'Internal server error',
  [ERROR_CODES.FORBIDDEN]: 'Forbidden',
  [ERROR_CODES.CONFLICT]: 'Conflict occurred',
  [ERROR_CODES.UNPROCESSABLE_ENTITY]: 'Unprocessable entity',

  // Provider specific
  [ERROR_CODES.KONGAPAY_OTP_RETRIES_LEFT]: 'OTP retries remaining',
  [ERROR_CODES.CARD_SERVICE_RETRIES_LEFT_ERROR_CODE]: 'Card service retries remaining',
  [ERROR_CODES.CARD_SERVICE_INSUFFICENT_BALANCE_CODE]: 'Insufficient balance',
  [ERROR_CODES.MANDATE_OTP_RETRIES_LEFT]: 'Mandate OTP retries remaining',

  // Customer & Data
  [ERROR_CODES.CUSTOMER_ID_NOT_FOUND]: 'Customer ID not found',
  [ERROR_CODES.MISSING_MERCHANT_REFERENCE]: 'Missing merchant reference',
  [ERROR_CODES.DUPLICATE_TRANSACTION]: 'Duplicate transaction detected',
} as const;

// HTTP Status Code mappings
export const ERROR_HTTP_STATUS = {
  [ERROR_CODES.INVALID_HASH]: 400,
  [ERROR_CODES.AUTHENTICATION_ERROR]: 401,
  [ERROR_CODES.AUTHORIZATION_ERROR]: 403,
  [ERROR_CODES.ACCESS_DENIED]: 403,
  [ERROR_CODES.TOKEN_EXPIRED]: 401,
  [ERROR_CODES.INVALID_TOKEN]: 401,
  [ERROR_CODES.TRANSACTION_NOT_FOUND]: 404,
  [ERROR_CODES.TRANSACTION_FAILED]: 400,
  [ERROR_CODES.INVALID_MERCHANT]: 401,
  [ERROR_CODES.FEATURE_DISABLED]: 503,
  [ERROR_CODES.INSUFFICIENT_BALANCE]: 400,
  [ERROR_CODES.INVALID_CARD]: 400,
  [ERROR_CODES.CARD_DECLINED]: 400,
  [ERROR_CODES.NETWORK_ERROR]: 502,
  [ERROR_CODES.TIMEOUT_ERROR]: 504,
  [ERROR_CODES.CIRCUIT_BREAKER_OPEN]: 503,
  [ERROR_CODES.PROVIDER_ERROR]: 502,
  [ERROR_CODES.VALIDATION_ERROR]: 400,
  [ERROR_CODES.RATE_LIMIT_EXCEEDED]: 429,
  [ERROR_CODES.NOT_FOUND]: 404,
  [ERROR_CODES.INTERNAL_SERVER_ERROR]: 500,
  [ERROR_CODES.REFUND_AMOUNT_EXCEEDED]: 400,
  [ERROR_CODES.SETTLEMENT_FAILED]: 500,
  [ERROR_CODES.INVALID_OTP]: 400,
  [ERROR_CODES.OTP_EXPIRED]: 400,
  [ERROR_CODES.CUSTOMER_ID_NOT_FOUND]: 400,
  [ERROR_CODES.MISSING_MERCHANT_REFERENCE]: 400,
} as const;

// Export type definitions
export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];
export type ErrorMessage = typeof ERROR_MESSAGES[keyof typeof ERROR_MESSAGES];